- name: Install dnf package for nfs-kernel-server 
  ansible.builtin.apt:
    name: nfs-kernel-server 
    state: latest

- name: Create directory for NFS exports if it does not exist
  ansible.builtin.file:
    path: /head/NFS
    state: directory
    mode: '0755'


- name: Export /head/NFS 
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: /head/NFS  compute*(rw,async) 
    create: yes

- name: Ensure nfs-kernel-server service restarted
  ansible.builtin.systemd:
    state: restarted
    name: nfs-kernel-server 
    enabled: yes
