  - name: Install apt packages on head node
    ansible.builtin.apt:
      name: gcc,openssl,numactl,hwloc,lua5.3,man2html,make,ruby,ruby-dev,libmunge-dev,libpam0g-dev,mariadb-server,libmariadb-dev-compat,libmariadb-dev,python3-pymysql,checkinstall,libpmix-dev
      state: latest

  - name:
    ansible.builtin.systemd:
      state: stopped
      name: mariadb

  - name: Ensure mariadb service is running
    ansible.builtin.systemd:
      state: started
      name: mariadb
      enabled: yes       

