---
# NFS Configuration Tasks

# On Head Node (NFS Server)
- name: Ensure NFS share directory exists on head node
  file:
    path: "{{ slurm_nfs_share }}"
    state: directory
    owner: root
    group: slurm
    mode: '0775'
  when: inventory_hostname in groups['head_node']

- name: Export NFS share from head node with best-practice options
  lineinfile:
    path: /etc/exports
    line: "{{ slurm_nfs_share }} *(rw,sync,no_root_squash,no_subtree_check,sec=sys)"
  when: inventory_hostname in groups['head_node']
  notify: Restart NFS Server

- name: Re-export NFS shares on head node
  command: exportfs -ra
  when: inventory_hostname in groups['head_node']

- name: Ensure NFS server is started on head node
  systemd:
    name: nfs-kernel-server
    enabled: yes
    state: started
  when: inventory_hostname in groups['head_node']

# On Compute Nodes (NFS Client)
- name: Ensure NFS mount directory exists on compute nodes
  file:
    path: "{{ slurm_nfs_mount }}"
    state: directory
    owner: root
    group: slurm
    mode: '0775'
  when: inventory_hostname in groups['compute']

- name: Configure NFS mount on compute nodes in /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ slurm_control_host }}:{{ slurm_nfs_share }} {{ slurm_nfs_mount }} nfs defaults 0 0"
  when: inventory_hostname in groups['compute']

- name: Wait until NFS share is mounted on compute nodes
  shell: mountpoint -q "{{ slurm_nfs_mount }}"
  register: mountpoint_check
  retries: 30
  delay: 10
  until: mountpoint_check.rc == 0
  when: inventory_hostname in groups['compute']

- name: Mount NFS share on compute nodes
  command: mount -a
  when: inventory_hostname in groups['compute']

# Handler for NFS server restart (in roles/nfs/handlers/main.yml)
