  - name: Install munge on compute nodes
    ansible.builtin.apt:
      name: munge
      state: latest

  - name: Copy mungekey with owner and permissions to the compute nodes
    ansible.builtin.copy:
     src: roles/head-node_munge_key/files/munge.key
     dest: /etc/munge/
     owner: munge
     group: munge
     mode: '0400'

  - name: Restart munge service after munge.key has been copied
    ansible.builtin.service:
     name: munge
     state: restarted
