---
# Munge Key Management Tasks

# On Head Node: Generate and copy Munge key to NFS share
- name: Generate Munge key if not already created on head node
  command: /usr/sbin/mungekey --create
  args:
    creates: "{{ munge_key_path }}"
  when: inventory_hostname in groups['head_node']

- name: Ensure Munge directory exists on NFS (head node)
  file:
    path: "{{ munge_nfs_path }}"
    state: directory
    owner: munge
    group: munge
    mode: '0755'
  when: inventory_hostname in groups['head_node']

- name: Copy Munge key to NFS share on head node
  copy:
    src: "{{ munge_key_path }}"
    dest: "{{ munge_nfs_path }}/munge.key"
    remote_src: yes
    owner: munge
    group: munge
    mode: '0400'
  when: inventory_hostname in groups['head_node']

# On Compute Nodes: Copy Munge key from NFS share to local directory
- name: Ensure local Munge directory exists on compute nodes
  file:
    path: "{{ munge_key_path | dirname }}"
    state: directory
    owner: munge
    group: munge
    mode: '0700'
  when: inventory_hostname in groups['compute']

- name: Copy Munge key from NFS to compute nodes
  copy:
    src: "{{ munge_nfs_path }}/munge.key"
    dest: "{{ munge_key_path }}"
    remote_src: yes
    owner: munge
    group: munge
    mode: '0400'
  when: inventory_hostname in groups['compute']

- name: Restart Munge service on all nodes
  systemd:
    name: munge
    state: restarted
    enabled: yes
