  - name: reset mariadb
    ansible.builtin.shell: |
         systemctl stop mariadm
         rm -rf /var/lib/mysql/*
         mysql_install_db --auth-root-authentication-method=normal

  - name: Copying mariadb-server.cnf into place
    ansible.builtin.copy:
     src: roles/slurmd/files/mariadb-server.cnf
     dest: /etc/mysql/conf.d/ 
     owner: root
     group: root

  - name: Restart mariadb service
    ansible.builtin.service:
      name: mariadb
      state: restarted

  - name: Create a new database named slurm_acct_db
    community.mysql.mysql_db:
      name: slurm_acct_db
      state: present

  - name: Create database user slurm with slurm_acct_db privileges
    community.mysql.mysql_user:
      name: slurm
      password: "lcilab2023"
      priv: 'slurm_acct_db.*:all,GRANT'
      state: present

  - name: Create & change ownership of /etc/slurm/
    file:
      path: /etc/slurm
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy slurm.conf into place with correct permissions
    ansible.builtin.copy:
     src: roles/slurmd/files/slurm.conf
     dest: /etc/slurm/
     owner: slurm
     group: slurm
     mode: '0755'

  - name: Copy slurmdbd.conf into place with correct permissions
    ansible.builtin.copy:
     src: roles/slurmd/files/slurmdbd.conf
     dest: /etc/slurm/
     owner: slurm
     group: slurm
     mode: '0600'

  - name: Copy cgroup.conf into place with correct permissions
    ansible.builtin.copy:
     src: roles/slurmd/files/cgroup.conf
     dest: /etc/slurm/

  - name: reload systemd
    ansible.builtin.shell: systemctl daemon-reload

  - name: Restart slurmdbd service
    ansible.builtin.service:
      name: slurmdbd
      enabled: yes
      state: restarted

  - name: Restart slurmctld service
    ansible.builtin.service:
      name: slurmctld
      enabled: yes
      state: restarted

  - name: Create slurm cluster name cluster
    ansible.builtin.command: /usr/bin/sacctmgr -i add cluster cluster
    ignore_errors: True
